/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.tripvi.measuretext;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import android.app.Activity;
import android.util.DisplayMetrics;

import android.text.StaticLayout;
// import android.text.Layout;
import android.text.TextPaint;
import android.text.Layout.Alignment;

import android.widget.TextView;
import android.util.TypedValue;

import android.graphics.Paint;
import android.graphics.Rect;

import android.content.res.Resources;

@Kroll.module(name="Measuretext", id="com.tripvi.measuretext")
public class MeasuretextModule extends KrollModule
{

	// Standard Debugging variables
	private static final String TAG = "MeasuretextModule";

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public MeasuretextModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(TAG, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}
	
	public float pxToDP(float px) {
		Activity activity = this.getActivity();
		
		Resources resources = activity.getResources();
	    DisplayMetrics metrics = resources.getDisplayMetrics();
	    
		float dp = px / (metrics.densityDpi / 160f);
	    
		return dp;
	}
	
	public int dpToPX(float dp) {
		Activity activity = this.getActivity();
		
		Resources resources = activity.getResources();
		DisplayMetrics metrics = resources.getDisplayMetrics();
		
		float px = dp * (metrics.densityDpi / 160f);
		
		return (int) px;
	}
	
	// Methods
	@Kroll.method
	public float measureTextWidth(String text, int fontSize, String unit)
	{
		Paint p = new Paint();
		TextView t = new TextView(this.getActivity());
		// Rect bounds = new Rect();
		int _unit;
		
		if (unit.equals("sp")) {
			_unit = TypedValue.COMPLEX_UNIT_SP;
		}
		else if (unit.equals("dp") || unit.equals("dip")) {
			_unit = TypedValue.COMPLEX_UNIT_DIP;
		}
		else  if (unit.equals("px")) {
			_unit = TypedValue.COMPLEX_UNIT_PX;
		}
		else if (unit.equals("pt")) {
			_unit = TypedValue.COMPLEX_UNIT_PT;
		}
		else {
			_unit = TypedValue.COMPLEX_UNIT_DIP;
		}
		
		t.setTextSize(_unit, fontSize);
		p.setTextSize(t.getTextSize());
		// p.getTextBounds(text, 0, text.length(), bounds);
		
		// float mt = p.measureText(s);
		// int bw = bounds.width();
		
		float width = pxToDP(p.measureText(text));
		Log.d(TAG, "\"" + text + "\" -> width = " + String.valueOf(width));

		return width;
	}
	
	// Methods
	@Kroll.method
	public float measureTextHeight(String text, int fontSize, String unit, int widthLimit)
	{
		TextView t = new TextView(this.getActivity());
		widthLimit = dpToPX(widthLimit);
		
		int _unit;
		
		if (unit.equals("sp")) {
			_unit = TypedValue.COMPLEX_UNIT_SP;
		}
		else if (unit.equals("dp") || unit.equals("dip")) {
			_unit = TypedValue.COMPLEX_UNIT_DIP;
		}
		else  if (unit.equals("px")) {
			_unit = TypedValue.COMPLEX_UNIT_PX;
		}
		else if (unit.equals("pt")) {
			_unit = TypedValue.COMPLEX_UNIT_PT;
		}
		else {
			_unit = TypedValue.COMPLEX_UNIT_DIP;
		}
		
		t.setTextSize(_unit, fontSize);
		
		StaticLayout layout = new StaticLayout(text, t.getPaint(), widthLimit, Alignment.ALIGN_NORMAL, 1.0f, 0.0f, true);
		// Layout layout = new Layout(text, t.getPaint(), widthLimit, Alignment.ALIGN_NORMAL, 1.0f, 0.0f);
		
		float height = pxToDP(layout.getHeight());
		
		Log.d(TAG, "\"" + text + "\" -> height = " + String.valueOf(height));
		
		return height;
	}

}

